version: "3.7"

volumes:
  node_modules:

networks:
  saip_search_network:
    external: true

services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP_USER_ID: ${APP_USER_ID:-1000}
        PROJECT_DIRECTORY: ${PROJECT_DIRECTORY:-/app}
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    volumes:
      - .:${PROJECT_DIRECTORY:-/app}:cached
      - ~/.ssh:/home/saip/.ssh
      - ~/.gitconfig:/home/saip/.gitconfig
    entrypoint: [ "/home/saip/docker-entrypoint.sh" ]
    command: ["yarn", "start"]
    networks:
      - saip_search_network
